services:
  - type: web
    name: medical-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false  # Set this manually in the Render dashboard

  - type: web
    name: medical-frontend
    env: static
    buildCommand: "cd medical-chatbot-frontend && npm install && npm run build"
    staticPublishPath: "medical-chatbot-frontend/build"
